name: RMV Appointment Checker

on:
  # Manual “Run workflow” button
  workflow_dispatch:
  # Every 5 minutes on the cron grid
  schedule:
    - cron: "*/5 * * * *"

jobs:
  check-appointment:
    runs-on: ubuntu-latest
    env:
      # Pushover credentials – add these in Settings → Secrets
      PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
      PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}

      # Loop settings (optional)
      LOOP_COUNT: 5
      SLEEP_SECONDS: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies & browsers
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests beautifulsoup4
          python -m playwright install

      - name: Run RMV appointment checker
        run: python check_appointment.py
