name: RMV Appointment Checker

# Only manual or API dispatch kicks it off;
# we rely on the chainer for continuous runs.
on:
  workflow_dispatch:

jobs:
  check-appointment:
    runs-on: ubuntu-latest
    # Must be ≥ 330 minutes; GitHub max is 360
    timeout-minutes: 360
    env:
      # your secrets
      PUSHOVER_USER_KEY: ${{ secrets.PUSHOVER_USER_KEY }}
      PUSHOVER_API_TOKEN: ${{ secrets.PUSHOVER_API_TOKEN }}

      # 5h30 loop
      LOOP_COUNT: 330 # 5.5 hrs × 60 min
      SLEEP_SECONDS: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies & browsers
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests beautifulsoup4
          python -m playwright install

      - name: Run RMV appointment checker
        run: python check_appointment.py
